# Write your MySQL query statement below
WITH TABLE1(NAME) AS (
SELECT S.NAME
FROM ORDERS E
JOIN COMPANY A
    ON E.COM_ID = A.COM_ID
JOIN SALESPERSON S
    ON E.SALES_ID = S.SALES_ID
where A.NAME = "RED"
GROUP BY S.SALES_ID
)
SELECT NAME
FROM SALESPERSON
WHERE NAME NOT IN (SELECT NAME FROM TABLE1);